version: "3.9"

services:
  db:
    image: postgres:15
    container_name: vetapp_db
    dockerfile: Dockerfile
    environment:
      POSTGRES_USER: vetapp_user
      POSTGRES_PASSWORD: y8pX4s9Kj3bQeT7mRzFh
      POSTGRES_DB: vetapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vetapp_backend
    env_file:
      - ./backend/.env.prod
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend/vet-app
      dockerfile: Dockerfile
    container_name: vetapp_frontend
    env_file:
      - ./frontend/vet-app/.env.prod
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:alpine
    container_name: vetapp_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  postgres_data:
